version: '3.8'

services:
  db:
    image: postgres:17
    container_name: recipe-book-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - recipe_pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: recipe-book-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  recipe_pgdata:
